### ISSUE TITLE
Add Humidity Adjustment?

### ISSUE THREAD

**Issue by rrmills7777** [RaresAil/homebridge-temperature-sensor-dht#5]
Like this plugin, as it's just about the simplest DHT22 plugin I've found.  I like that you have a temperature offset, what about a humidity offset?  I have a couple of DHT22s that consistently read 7-8% higher than a calibrated hygrometer nearby, would be nice to be able to account for this.

**Comment by RaresAil** [comment]
Hey, I will work on it

**Comment by RaresAil** [comment]
@rrmills7777 Sorry for the delay, the version 1.0.4 has humidity adjustment
